import { expect, test, type Page, type TestInfo } from '@playwright/test'
import sharp from 'sharp'

const markerUrl = '/?location=YS-001'
const unwantedCopy = /가스온|가상\s*현장|시[연현]용|굴착\s*주의\s*영역|신고\s*내역|홈\s*화면에\s*추가|시민의식|샘플|sample|워터마크|watermark/i

async function frame(page: Page) {
  await page.evaluate(async () => {
    await document.fonts.ready
    await new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve())))
  })
}
async function capture(page: Page, info: TestInfo, screen: string) {
  await frame(page)
  await page.screenshot({ path: `artifacts/screenshots/${info.project.name}-${screen}.png`, fullPage: true, animations: 'disabled' })
}
async function checkLayout(page: Page) {
  const size = await page.evaluate(() => ({ content: document.documentElement.scrollWidth, viewport: window.innerWidth }))
  expect(size.content).toBeLessThanOrEqual(size.viewport + 1)
  expect(await page.locator('body').innerText()).not.toMatch(unwantedCopy)
}
async function authenticate(page: Page) {
  await page.goto(`${markerUrl}#login`)
  await page.getByRole('button', { name: '시험용 정보 자동입력', exact: true }).click()
  await page.getByRole('button', { name: '현장 확인', exact: true }).click()
  await expect(page).toHaveURL(/location=YS-001#worker$/)
  await page.getByRole('button', { name: /3D 배관 보기/ }).click()
  await expect(page.locator('canvas')).toBeVisible()
  await expect(page.getByRole('button', { name: '수소 GP-001 상세 정보', exact: true })).toBeVisible()
}
function collectErrors(page: Page) {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  return errors
}

async function fitsScreen(page: Page) {
  const size = await page.evaluate(() => ({ width: document.documentElement.scrollWidth, height: document.documentElement.scrollHeight, viewportWidth: innerWidth, viewportHeight: innerHeight }))
  expect(size.width).toBeLessThanOrEqual(size.viewportWidth + 1)
  expect(size.height).toBeLessThanOrEqual(size.viewportHeight + 1)
}

test('공개 안내와 작업자 메뉴가 구분되고 첫 화면과 로그인은 스크롤 없이 보인다', async ({ page }, testInfo) => {
  await page.goto(markerUrl)
  const nav = page.getByRole('navigation', { name: '이용자별 메뉴' })
  await expect(nav.getByRole('button', { name: '공사 안내 누구나 이용' })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('heading', { name: '한빛산단 앞 도로', exact: true })).toBeVisible()
  await expect(page.locator('a[href*="eocs.or.kr"]')).toHaveCount(0)
  await expect(page.locator('canvas')).toBeVisible()
  await fitsScreen(page)
  await capture(page, testInfo, 'home')
  await page.getByRole('button', { name: '위험요소 신고', exact: true }).click()
  await expect(page.getByRole('heading', { name: '위험요소 신고', exact: true })).toBeVisible()
  await nav.getByRole('button', { name: '현장 업무 접수번호로 확인' }).click()
  await expect(page.getByRole('heading', { name: '작업 현장 확인', exact: true })).toBeVisible()
  await expect(nav.getByRole('button', { name: '현장 업무 접수번호로 확인' })).toHaveAttribute('aria-current', 'page')
  await expect(page.locator('canvas')).toHaveCount(0)
  await expect(page.getByLabel('공사 신고 접수번호', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('현장 비밀번호', { exact: true })).toHaveValue('')
  await expect(page.locator('.demo-account')).toContainText('DEMO-2026-001')
  await expect(page.locator('.demo-account')).toContainText('1234')
  await fitsScreen(page)
  await capture(page, testInfo, 'login')
  await page.getByRole('button', { name: '시험용 정보 자동입력', exact: true }).click()
  await expect(page.getByLabel('공사 신고 접수번호', { exact: true })).toHaveValue('DEMO-2026-001')
  await expect(page.getByLabel('현장 비밀번호', { exact: true })).toHaveValue('1234')
  await expect(page.getByRole('heading', { name: '작업 현장 확인', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '현장 확인', exact: true }).click()
  await expect(page.getByRole('heading', { name: '작업 전 배관 확인', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /지하 투시 AR/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /3D 배관 보기/ })).toBeVisible()
  await fitsScreen(page)
  await page.reload()
  await expect(page.getByRole('heading', { name: '작업 전 배관 확인', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  await page.goto(`${markerUrl}#worker`)
  await expect(page.getByRole('heading', { name: '작업 현장 확인', exact: true })).toBeVisible()
  await page.goto('/?location=UNKNOWN-999#worker')
  await expect(page.getByRole('heading', { name: '등록되지 않은 QR입니다', exact: true })).toBeVisible()
  await expect(page.locator('canvas')).toHaveCount(0)
})

test('AR 직접 주소도 로그인 후 열리고 잘못된 비밀번호는 거부한다', async ({ page }) => {
  await page.goto(`${markerUrl}#ar`)
  await expect(page.getByRole('heading', { name: '작업 현장 확인', exact: true })).toBeVisible()
  await expect(page.locator('canvas')).toHaveCount(0)
  await page.getByRole('button', { name: '시험용 정보 자동입력', exact: true }).click()
  await page.getByLabel('현장 비밀번호', { exact: true }).fill('wrong')
  await page.getByRole('button', { name: '현장 확인', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('접수번호와 현장 비밀번호를 확인하세요.')
  await expect(page.locator('canvas')).toHaveCount(0)
  await page.getByRole('button', { name: '시험용 정보 자동입력', exact: true }).click()
  await page.getByRole('button', { name: '현장 확인', exact: true }).click()
  await expect(page).toHaveURL(/#ar$/)
  await expect(page.getByRole('heading', { name: '지하 투시 AR', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'AR 닫기', exact: true }).click()
  await expect(page.getByRole('heading', { name: '작업 전 배관 확인', exact: true })).toBeVisible()
})

test('사진 형식/용량을 검사하고 위험요소 신고 내용을 저장하여 새로고침 후에도 확인한다', async ({ page }, testInfo) => {
  await page.goto(`${markerUrl}#report`)
  await expect(page.getByLabel('위치', { exact: true })).toHaveValue('YS-001 / 한빛산단 (예시)')
  await expect(page.getByLabel('위치', { exact: true })).toHaveAttribute('readonly', '')
  await page.getByRole('button', { name: '신고 내용 저장', exact: true }).click()
  expect(await page.getByLabel('작업 내용', { exact: true }).evaluate((el: HTMLTextAreaElement) => el.validity.valueMissing)).toBe(true)
  const upload = page.locator('input[type="file"]')
  await upload.setInputFiles({ name: 'invalid.txt', mimeType: 'text/plain', buffer: Buffer.from('not an image') })
  await expect(page.getByRole('alert')).toContainText('JPG, PNG, WEBP 또는 GIF')
  await upload.setInputFiles({ name: 'too-large.png', mimeType: 'image/png', buffer: Buffer.alloc(10 * 1024 * 1024 + 1) })
  await expect(page.getByRole('alert')).toContainText('10MB 이하')
  await upload.setInputFiles({ name: 'site-photo.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==', 'base64') })
  const preview = page.getByRole('img', { name: '선택한 현장 사진', exact: true })
  await expect(preview).toBeVisible()
  await expect.poll(() => preview.evaluate((el: HTMLImageElement) => el.naturalWidth)).toBeGreaterThan(0)
  await page.getByRole('button', { name: '사진 삭제', exact: true }).click()
  await expect(preview).toHaveCount(0)
  const reason = '도로 가장자리에서 굴착기 작업 중이며 현장 공사 안내 확인이 필요합니다.'
  await page.getByLabel('작업 내용', { exact: true }).fill(reason)
  await expect(page.getByText(/기관 전송 미연결/)).toBeVisible()
  await checkLayout(page)
  await page.getByRole('button', { name: '신고 내용 저장', exact: true }).click()
  await expect(page).toHaveURL(/location=YS-001#complete$/)
  await expect(page.getByRole('heading', { name: '신고 내용 저장 완료', exact: true })).toBeVisible()
  await expect(page.getByText('이 기기에 저장되었습니다. 기관으로 전송되지는 않았습니다.', { exact: true })).toBeVisible()
  await expect(page.getByText(reason, { exact: true })).toBeVisible()
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.getByText(reason, { exact: true })).toBeVisible()
  await checkLayout(page)
  await capture(page, testInfo, 'report-saved')
})

test('전체/평면/도로 단면/교차부가 다르게 렌더링되고 회전과 로그아웃이 동작한다', async ({ page }, testInfo) => {
  test.setTimeout(120_000)
  const errors = collectErrors(page)
  await authenticate(page)
  const canvas = page.locator('canvas')
  const rendered: Buffer[] = []
  for (const [label, filename] of [['전체 3D', 'viewer-3d'], ['평면', 'viewer-plan'], ['도로 단면', 'viewer-section'], ['교차부', 'viewer-crossing']]) {
    const button = page.getByRole('button', { name: label, exact: true })
    await button.click()
    await expect(button).toHaveAttribute('aria-pressed', 'true')
    await frame(page)
    if (rendered.length) await expect.poll(async () => (await canvas.screenshot()).equals(rendered[rendered.length - 1])).toBe(false)
    const image = await canvas.screenshot()
    const stats = await sharp(image).stats()
    expect(Math.max(...stats.channels.slice(0, 3).map(channel => channel.stdev))).toBeGreaterThan(5)
    for (const previous of rendered) expect(image.equals(previous)).toBe(false)
    rendered.push(image)
    if (label === '도로 단면') await expect(page.getByText('지표 0 m', { exact: true })).toBeVisible()
    if (label === '교차부') await expect(page.locator('.crossing-clearance')).toContainText('0.75 m')
    await checkLayout(page)
    await capture(page, testInfo, filename)
  }
  await page.getByRole('button', { name: '전체 3D', exact: true }).click()
  await canvas.scrollIntoViewIfNeeded()
  await frame(page)
  const bounds = await canvas.boundingBox()
  expect(bounds).not.toBeNull()
  if (bounds) {
    // Prove the drag moved the camera from the renderer state, then confirm the canvas repainted.
    // Under heavy load, page-level screenshots can return a stale compositor frame even though the
    // scene rotated, so the pixel check uses the canvas element with a generous timeout.
    const readCamera = () => page.evaluate(async () => {
      const url = performance.getEntriesByType('resource').map(entry => entry.name).find(name => name.includes('react-three_fiber'))!
      const fiber = await import(/* @vite-ignore */ url)
      const state = fiber._roots.get(document.querySelector('canvas')).store.getState()
      return state.camera.position.toArray().map((value: number) => Number(value.toFixed(2))) as number[]
    })
    const cameraBefore = await readCamera()
    const before = await canvas.screenshot()
    const start = { x: bounds.x + bounds.width * 0.75, y: bounds.y + bounds.height * 0.3 }
    await page.mouse.move(start.x, start.y)
    await expect.poll(() => page.evaluate(({ x, y }) => document.elementFromPoint(x, y)?.tagName, start)).toBe('CANVAS')
    await frame(page)
    await page.mouse.down()
    await page.mouse.move(bounds.x + bounds.width * 0.45, bounds.y + bounds.height * 0.55, { steps: 12 })
    await page.mouse.up()
    await frame(page)
    await expect.poll(readCamera, { timeout: 15_000 }).not.toEqual(cameraBefore)
    await expect.poll(async () => (await canvas.screenshot()).equals(before), { timeout: 30_000 }).toBe(false)
  }
  await page.getByRole('button', { name: '시점 초기화', exact: true }).click()
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  await page.goto(`${markerUrl}#worker`)
  await expect(page.getByRole('heading', { name: '작업 현장 확인', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('관로 심도/규격과 시설 필터/보호판 분리/레이어 표시가 선택에 맞춰 동작한다', async ({ page }, testInfo) => {
  test.setTimeout(100_000)
  const errors = collectErrors(page)
  await authenticate(page)
  const facility = page.getByRole('combobox', { name: '시설 선택', exact: true })
  expect(await facility.locator('option').count()).toBeGreaterThanOrEqual(20)
  const detail = page.getByRole('region', { name: '선택한 시설', exact: true })
  await facility.selectOption('WP-003')
  for (const text of ['공업용수 횡단관', '3.55', '600', '수직 순이격 0.75 m']) await expect(detail).toContainText(text)
  await facility.selectOption('SW-001')
  await expect(detail).toContainText('1200')
  await expect(detail).toContainText('철근 콘크리트관')
  await facility.selectOption('EL-001')
  await expect(detail).toContainText('150 mm × 6공')
  await page.getByRole('button', { name: '시설 목록', exact: true }).click()
  await page.locator('.system-filter').getByRole('button', { name: '구조물', exact: true }).click()
  const list = page.locator('.facility-list')
  await expect(list.getByRole('button')).toHaveCount(4)
  await list.getByRole('button', { name: /보호판.*PL-001/ }).click()
  await expect(facility).toHaveValue('PL-001')
  await page.getByRole('button', { name: '상세 정보', exact: true }).click()
  await expect(detail).toContainText('2.0 × 2.3 × 0.18 m')
  const canvas = page.locator('canvas')
  const before = await canvas.screenshot()
  await page.getByRole('button', { name: '보호판 분리', exact: true }).click()
  await expect(page.getByRole('button', { name: '보호판 분리', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(async () => (await canvas.screenshot()).equals(before)).toBe(false)
  await capture(page, testInfo, 'viewer-plates')
  await page.getByRole('button', { name: '표시 설정', exact: true }).click()
  const structureSwitch = page.getByRole('switch', { name: '보호판/구조물', exact: true })
  await structureSwitch.click()
  await expect(structureSwitch).toHaveAttribute('aria-checked', 'false')
  await expect(page.getByRole('button', { name: '보호판 PL-001 상세 정보', exact: true })).toHaveCount(0)
  await facility.selectOption('PL-002')
  await expect(structureSwitch).toHaveAttribute('aria-checked', 'true')
  await expect(page.getByRole('button', { name: '복공판 PL-002 상세 정보', exact: true })).toBeVisible()
  await facility.selectOption('WP-001')
  const utilities = page.getByRole('switch', { name: '상하수/전력/통신', exact: true })
  await utilities.click()
  await expect(page.getByRole('button', { name: '공업용수 WP-001 상세 정보', exact: true })).toHaveCount(0)
  await utilities.click()
  await expect(page.getByRole('button', { name: '공업용수 WP-001 상세 정보', exact: true })).toBeVisible()
  await facility.selectOption('GP-001')
  const labels = page.getByRole('switch', { name: '선택 정보', exact: true })
  await labels.click()
  await expect(page.getByRole('button', { name: '수소 GP-001 상세 정보', exact: true })).toHaveCount(0)
  await labels.click()
  await expect(page.getByRole('button', { name: '수소 GP-001 상세 정보', exact: true })).toBeVisible()
  await expect(page.locator('.context-map-label').first()).toHaveCSS('filter', 'none')
  await page.getByRole('switch', { name: '주변 건물/도로', exact: true }).click()
  await expect(page.locator('.context-map-label')).toHaveCount(0)
  await page.getByRole('slider', { name: '노면 표시', exact: true }).press('End')
  await expect(page.getByRole('slider', { name: '노면 표시', exact: true })).toHaveValue('0.85')
  await checkLayout(page)
  expect(errors).toEqual([])
})

test('QR은 쿼리와 현장 코드를 보존하고 자격증명 주소를 거부하며 PNG로 저장된다', async ({ page }, testInfo) => {
  await page.goto(`${markerUrl}#qr`)
  await expect(page.getByRole('img', { name: '현장 접속 QR', exact: true })).toBeVisible()
  const markerDownload = page.getByRole('link', { name: '안내판 저장', exact: true })
  const markerPrint = page.getByRole('link', { name: '인쇄용 안내판', exact: true })
  await expect(markerDownload).toBeVisible()
  await expect(markerDownload).toHaveAttribute('href', '/qr/YS-001-marker.png')
  await expect(markerDownload).toHaveAttribute('download', 'YS-001-현장안내판.png')
  await expect(markerPrint).toBeVisible()
  await expect(markerPrint).toHaveAttribute('href', '/qr/YS-001.html')
  await checkLayout(page)
  await page.getByText('연결 주소 변경', { exact: true }).click()
  await page.getByLabel('웹페이지 주소', { exact: true }).fill('https://demo:secret@example.com/field')
  await page.getByRole('button', { name: 'QR 생성', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('http:// 또는 https:// 주소를 입력하세요.')
  await page.getByLabel('웹페이지 주소', { exact: true }).fill('https://example.com/field?source=qr&location=OLD#login')
  await page.getByRole('button', { name: 'QR 생성', exact: true }).click()
  await expect(page.getByText('https://example.com/field?source=qr&location=YS-001', { exact: true })).toBeVisible()
  await expect(markerDownload).toHaveCount(0)
  await expect(markerPrint).toHaveCount(0)
  await expect(page.getByRole('img', { name: '현장 접속 QR', exact: true })).toHaveAttribute('src', /^data:image\/png;base64,/)
  const pending = page.waitForEvent('download')
  await page.getByRole('link', { name: 'QR 저장', exact: true }).click()
  const download = await pending
  expect(download.suggestedFilename()).toBe('QR-YS-001.png')
  expect(await download.failure()).toBeNull()
  const path = await download.path()
  expect(path).not.toBeNull()
  const metadata = await sharp(path!).metadata()
  expect(metadata.format).toBe('png')
  expect(metadata.width).toBe(1200)
  await checkLayout(page)
  await capture(page, testInfo, 'qr')
})
